#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pugixml
Version  : 1.8
Release  : 1
URL      : http://github.com/zeux/pugixml/releases/download/v1.8/pugixml-1.8.tar.gz
Source0  : http://github.com/zeux/pugixml/releases/download/v1.8/pugixml-1.8.tar.gz
Summary  : Light-weight, simple and fast XML parser for C++ with XPath support.
Group    : Development/Tools
License  : MIT
Requires: pugixml-lib
BuildRequires : cmake

%description
pugixml 1.8 - an XML processing library
Report bugs and download new versions at http://pugixml.org/

%package dev
Summary: dev components for the pugixml package.
Group: Development
Requires: pugixml-lib
Provides: pugixml-devel

%description dev
dev components for the pugixml package.


%package lib
Summary: lib components for the pugixml package.
Group: Libraries

%description lib
lib components for the pugixml package.


%prep
%setup -q -n pugixml-1.8

%build
export LANG=C
mkdir clr-build
pushd clr-build
cmake .. -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS:BOOL=ON -DLIB_INSTALL_DIR:PATH=%{_libdir} -DCMAKE_AR=/usr/bin/gcc-ar -DLIB_SUFFIX=64 -DCMAKE_RANLIB=/usr/bin/gcc-ranlib
make VERBOSE=1  %{?_smp_mflags}
popd

%install
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)
/usr/lib64/cmake/pugixml/pugixml-config-noconfig.cmake
/usr/lib64/cmake/pugixml/pugixml-config.cmake

%files dev
%defattr(-,root,root,-)
/usr/include/*.hpp
/usr/lib64/libpugixml.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpugixml.so.1
/usr/lib64/libpugixml.so.1.8
