#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pugixml
Version  : 1.9
Release  : 9
URL      : https://github.com/zeux/pugixml/releases/download/v1.9/pugixml-1.9.tar.gz
Source0  : https://github.com/zeux/pugixml/releases/download/v1.9/pugixml-1.9.tar.gz
Summary  : Light-weight, simple and fast XML parser for C++ with XPath support.
Group    : Development/Tools
License  : MIT
Requires: pugixml-lib = %{version}-%{release}
BuildRequires : buildreq-cmake

%description
pugixml 1.9 - an XML processing library
Report bugs and download new versions at http://pugixml.org/

%package dev
Summary: dev components for the pugixml package.
Group: Development
Requires: pugixml-lib = %{version}-%{release}
Provides: pugixml-devel = %{version}-%{release}
Requires: pugixml = %{version}-%{release}

%description dev
dev components for the pugixml package.


%package lib
Summary: lib components for the pugixml package.
Group: Libraries

%description lib
lib components for the pugixml package.


%prep
%setup -q -n pugixml-1.9
cd %{_builddir}/pugixml-1.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1604354262
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1604354262
rm -rf %{buildroot}
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/pugiconfig.hpp
/usr/include/pugixml.hpp
/usr/lib64/cmake/pugixml/pugixml-config-relwithdebinfo.cmake
/usr/lib64/cmake/pugixml/pugixml-config.cmake
/usr/lib64/libpugixml.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libpugixml.so.1
/usr/lib64/libpugixml.so.1.9
